# Generated by Django 2.1 on 2019-10-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
