"""
Django settings for MyBlog project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p#tfvwo+7uht$4fow@4r-c18p5fzx(vop@(z)u%&jivq4dyqt6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'article',
	'userprofile',
	'password_reset',  # 第三方模块的注册
	'comment',
	'taggit',  # 第三方模块的注册
	'ckeditor',
	'mptt',
	'notifications',
	'notice',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyBlog.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'MyBlog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, "static"),
)
STATIC_URL = '/static/'

# SMTP服务器，改为你的邮箱的smtp!
EMAIL_HOST = 'smtphz.qiye.163.com'
# 改为你自己的邮箱名！
EMAIL_HOST_USER = 'xiang.wu@dessmann.com.cn'
# 你的邮箱密码
EMAIL_HOST_PASSWORD = 'Dsm188'
# 发送邮件的端口
EMAIL_PORT = 25
# 是否使用 TLS
EMAIL_USE_TLS = True
# 默认的发件人
DEFAULT_FROM_EMAIL = 'wx的博客 <xiang.wu@dessmann.com.cn>'

# 媒体文件地址
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CKEDITOR_CONFIGS = {
	# django-ckeditor默认使用default配置
	'default': {
		# 编辑器宽度自适应
		'width': 'auto',
		'height': '250px',
		# tab键转换空格数
		'tabSpaces': 4,
		# 工具栏风格
		'toolbar': 'Custom',
		# 工具栏按钮
		'toolbar_Custom': [
			# 表情 代码块
			['Smiley', 'CodeSnippet'],
			# 字体风格
			['Bold', 'Italic', 'Underline', 'RemoveFormat', 'Blockquote'],
			# 字体颜色
			['TextColor', 'BGColor'],
			# 链接
			['Link', 'Unlink'],
			# 列表
			['NumberedList', 'BulletedList'],
			# 最大化
			['Maximize']
		],
		# 加入代码块插件
		'extraPlugins': ','.join(['codesnippet']),
		'extraPlugins': ','.join(['codesnippet', 'prism', 'widget', 'lineutils']),
	}
}
